### PR TITLE
Add mutect2

### PR DESCRIPTION
**Pull request by wintun12**
- adding nextflow.config file
- adding bin folder containing source code, licence and sentieon package
- adding main.nf file
- adding module folder that contain mutect2 module
- update readme file

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_nextflow/1)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 112 of 112 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_nextflow/1)* status: all files reviewed, 5 unresolved discussions (waiting on @chrispyatt and @wintun12)

___
*[`main.nf` line 13 at r1](https://reviewable.io/reviews/eastgenomics/mutect2_nextflow/1#-Ne87HO_4Z5ZzhDB7l--:-Ne87HO_4Z5ZzhDB7l-0:bdzzdcy) ([raw file](https://github.com/eastgenomics/mutect2_nextflow/blob/031156e8affa179eacdcd196801bf5df9fadebac/main.nf#L13)):*
> ```Nextflow
>                 .fromFilePairs(params.bam_files,size: 2)
>     TNHaplotyper2(read_pairs_ch, params.fastaFile, params.fastaIndex,params.gatkResource)
>         
> ```

Whitespace



_Code quote:_
```Nextflow
·······
```
___
*[`modules/TNHaplotyper2/main.nf` line 6 at r1](https://reviewable.io/reviews/eastgenomics/mutect2_nextflow/1#-Ne88AQw-FAHEa7iM-Gs:-Ne88AQw-FAHEa7iM-Gt:bdzzdcy) ([raw file](https://github.com/eastgenomics/mutect2_nextflow/blob/031156e8affa179eacdcd196801bf5df9fadebac/modules/TNHaplotyper2/main.nf#L6)):*
> ```Nextflow
>     publishDir params.outdir, mode:'copy'
>     tag "${reads[0]}, ${reads[1]}"
>     
> ```

Whitespace
___
*[`modules/TNHaplotyper2/main.nf` line 12 at r1](https://reviewable.io/reviews/eastgenomics/mutect2_nextflow/1#-Ne87lSJ1JdF4CnCUGY9:-Ne87lSJ1JdF4CnCUGYA:bdzzdcy) ([raw file](https://github.com/eastgenomics/mutect2_nextflow/blob/031156e8affa179eacdcd196801bf5df9fadebac/modules/TNHaplotyper2/main.nf#L12)):*
> ```Nextflow
>         path fastaIndex
>         path gatkResource
>         
> ```

Whitespace



_Code quote:_
```Nextflow
·······
```
___
*[`modules/TNHaplotyper2/main.nf` line 18 at r1](https://reviewable.io/reviews/eastgenomics/mutect2_nextflow/1#-Ne87oZ15x2NjVYexnCJ:-Ne87oZ15x2NjVYexnCK:bdzzdcy) ([raw file](https://github.com/eastgenomics/mutect2_nextflow/blob/031156e8affa179eacdcd196801bf5df9fadebac/modules/TNHaplotyper2/main.nf#L18)):*
> ```Nextflow
>         path "*_markdup_recalibrated_tnhaplotyper2.vcf.gz.tbi"
> 
>     
> ```

Whitespace



_Code quote:_
```Nextflow
···
```
___
*[`modules/TNHaplotyper2/main.nf` line 21 at r1](https://reviewable.io/reviews/eastgenomics/mutect2_nextflow/1#-Ne87snO0yoP_L6wJB1b:-Ne87snO0yoP_L6wJB1c:bdzzdcy) ([raw file](https://github.com/eastgenomics/mutect2_nextflow/blob/031156e8affa179eacdcd196801bf5df9fadebac/modules/TNHaplotyper2/main.nf#L21)):*
> ```Nextflow
>     script:
> 
>         """          
> ```

Whitespace



_Code quote:_
```Nextflow
··········
```

**Review by chrispyatt — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_nextflow/1)* status: 111 of 112 files reviewed, 6 unresolved discussions (waiting on @mattgarner and @wintun12)

___
*[`main.nf` line 10 at r2](https://reviewable.io/reviews/eastgenomics/mutect2_nextflow/1#-Ne8GDsJ4-SxTXoZ2AhK:-Ne8GDsJ4-SxTXoZ2AhL:bjdfvlp) ([raw file](https://github.com/eastgenomics/mutect2_nextflow/blob/d40397cd4f3f3aad1fe94787c5ecb75e6892ccf0/main.nf#L10)):*
> ```Nextflow
>                 .fromFilePairs(params.bam_files,size: 2)
>     //run TNHaplotyper2 process from TNHaplotyper2 module
>     TNHaplotyper2(read_pairs_ch, params.fastaFile, params.fastaIndex,params.gatkResource)
> ```

think you're missing a space between these terms: params.fastaIndex,params.gatkResource

**Comment by wintun12** [comment]
Ah yes, sorry, missed those ones. Changed now.
________________________________

**Review by chrispyatt — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_nextflow/1)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @wintun12)

**Review by mattgarner — COMMENTED** [review]
> Reviewed 3 of 5 files at r2, 1 of 2 files at r4, all commit messages.
> Dismissed @mattgarner from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_nextflow/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wintun12)

___
*[`modules/TNHaplotyper2/main.nf` line 6 at r1](https://reviewable.io/reviews/eastgenomics/mutect2_nextflow/1#-Ne88AQw-FAHEa7iM-Gs:-Ne8UyeS9HQe1yttcpV3:bb6un1j) ([raw file](https://github.com/eastgenomics/mutect2_nextflow/blob/031156e8affa179eacdcd196801bf5df9fadebac/modules/TNHaplotyper2/main.nf#L6)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Whitespace
</blockquote></details>

Done
___
*[`modules/TNHaplotyper2/main.nf` line 12 at r1](https://reviewable.io/reviews/eastgenomics/mutect2_nextflow/1#-Ne87lSJ1JdF4CnCUGY9:-Ne8V1em671qwwNeFWT-:bb6un1j) ([raw file](https://github.com/eastgenomics/mutect2_nextflow/blob/031156e8affa179eacdcd196801bf5df9fadebac/modules/TNHaplotyper2/main.nf#L12)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Whitespace
</blockquote></details>

Done
___
*[`modules/TNHaplotyper2/main.nf` line 18 at r1](https://reviewable.io/reviews/eastgenomics/mutect2_nextflow/1#-Ne87oZ15x2NjVYexnCJ:-Ne8V3ai1aCxBAW7NZrM:bb6un1j) ([raw file](https://github.com/eastgenomics/mutect2_nextflow/blob/031156e8affa179eacdcd196801bf5df9fadebac/modules/TNHaplotyper2/main.nf#L18)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Whitespace
</blockquote></details>

Done
___
*[`modules/TNHaplotyper2/main.nf` line 21 at r1](https://reviewable.io/reviews/eastgenomics/mutect2_nextflow/1#-Ne87snO0yoP_L6wJB1b:-Ne8V4-E71K30EVFJ0iV:bb6un1j) ([raw file](https://github.com/eastgenomics/mutect2_nextflow/blob/031156e8affa179eacdcd196801bf5df9fadebac/modules/TNHaplotyper2/main.nf#L21)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Whitespace
</blockquote></details>

Done

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_nextflow/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wintun12)

**Review by chrispyatt — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_nextflow/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wintun12)

**Review by chrispyatt — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_nextflow/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wintun12)

**Pull request merged**
